backend:
  name: git-gateway
  branch: main
media_folder: assets/images
public_folder: /assets/images
media_library:
  name: uploadcare
collections:
  - name: blog
    folder: content/blog
    slug: "{{year}}-{{month}}-{{slug}}"
    preview_path: blog/{{slug}}
